### ISSUE TITLE
测试过程偶尔会遇到崩溃的现象报错如下

### ISSUE THREAD

**Issue by zpswz** [zhaolewei/ZlwAudioRecorder#24]
java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Bundle android.content.Intent.getExtras()' on a null object reference
	at com.zlw.main.recorderlib.recorder.RecordService.onStartCommand(RecordService.java:59)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3700)
	at android.app.ActivityThread.access$1700(ActivityThread.java:200)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1704)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6810)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by zpswz** [comment]
偶尔出现  目前我在onStartCommand加了个intent==null的判断  但是不知道为什么会null掉

**Comment by zhaolewei** [comment]
fix

**Comment by zhaolewei** [comment]
服务挂掉重启时可能为空
