### ISSUE TITLE
我有初始化，但是还是报错初始化失败

### ISSUE THREAD

**Issue by 1335987402** [zhaolewei/ZlwAudioRecorder#51]
1， RecordManager.getInstance().init(ChatApplication.appLication,true)

2，RecordManager.getInstance().start()

RecordHelper$AudioRecordThread.startPcmRecorder(RecordHelper.java:305)===============> startRecording() called on an uninitialized AudioRecord.
 java.lang.IllegalStateException: startRecording() called on an uninitialized AudioRecord.
        at android.media.AudioRecord.startRecording(AudioRecord.java:1110)
        at com.zlw.main.recorderlib.recorder.RecordHelper$AudioRecordThread.startPcmRecorder(RecordHelper.java:288)
        at com.zlw.main.recorderlib.recorder.RecordHelper$AudioRecordThread.run(RecordHelper.java:276)

**Comment by 1335987402** [comment]
是有的手机成功，有的手机就这样

**Comment by hxgqh** [comment]
什么原因导致的？我也出现了
