### ISSUE TITLE
安卓11，小米手机崩溃

### ISSUE THREAD

**Issue by funnull** [zhaolewei/ZlwAudioRecorder#56]

**Comment by MengYaoSai** [comment]
这是报错信息
java.lang.RuntimeException: Unable to start service com.zlw.main.recorderlib.recorder.RecordService@670d8aa with Intent { cmp=com.example.demo/com.zlw.main.recorderlib.recorder.RecordService (has extras) }: java.lang.NullPointerException
 at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4409)
 at android.app.ActivityThread.access$1900(ActivityThread.java:246)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1993)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loop(Looper.java:236)
 at android.app.ActivityThread.main(ActivityThread.java:7876)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
Caused by: java.lang.NullPointerException
 at java.io.File.<init>(File.java:283)
 at com.zlw.main.recorderlib.recorder.RecordHelper.start(RecordHelper.java:100)
 at com.zlw.main.rec

**Comment by zhaolewei** [comment]
v1.16修复
